plugins {
    id 'java'
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':common')

    // REST API
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    // Service Discovery
    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'

    // Event
    implementation 'org.springframework.kafka:spring-kafka'

    // Slack
    implementation 'com.slack.api:slack-api-client:1.48.0'

    // Health Check / Monitoring
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    runtimeOnly 'io.micrometer:micrometer-registry-prometheus'

    // Tracing
    implementation 'io.micrometer:micrometer-tracing-bridge-brave'
    implementation 'io.zipkin.reporter2:zipkin-reporter-brave'

    // Test
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}